config/routes.rb
Fopic::Application.routes.draw do
  resources :comments

  root :to => 'photos#index'
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :event

  resources :photos
  

  devise_for :users
  

  resources :photos do
    member do
      get :picture
    end

    collection do
      get :all
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  attr_accessible :comment, :good, :photo_id, :user_id
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
  attr_protected :user_id
  belongs_to :user


end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :content_type, :explanation, :picture_data, :title, :picture_file, :day, :eat, :user_id
  belongs_to :user
  has_many :comment

  def picture_file= (p)
    if p
      self.picture_data = p.read
      self.content_type = p.content_type
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photo 
  has_many :comment
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_filter :authenticate_user!

  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    

    @event_strips = Event.event_strips_for_month(
      @shown_month,
      0,
      :conditions => {:user_id => current_user.id})
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    @photo_id = params[:id]
    $photo_id = @photo_id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @comment }
    end

  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to  :controller => "photos", :action => "show",  :id => $photo_id }
        format.json { render :json => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, :notice => 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController

def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }

      else
        format.html { render :action => "new" }

      end
    end
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb

    end
  end


def show
   @event = Event.find(params[:id])

   respond_to do |format|
     format.html # show.html.erb
     format.json { render :json => @event }
   end
 end

  def index
    @event = Event.new
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def all
    @photos = Photo.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
    redirect_to("/")
  end

  def picture
    @photo = Photo.find(params[:id])
    send_data(@photo.picture_data, :type => @photo.content_type)
  end
 
  
  # GET /photos
  # GET /photos.json
  def index
    @filter = params[:filter]
    if @filter == "all" then
      @photos = Photo.find(:all, :order => "day DESC, eat ASC")
    elsif @filter == "without_me" then
      @photos = Photo.find(:all, :conditions => ["user_id not in (?)", current_user.id], :order => "day DESC, eat ASC")
    elsif @filter == "onlu_me" then
      @photos = Photo.find(:all, :conditions => ["user_id = ?", current_user.id], :order => "day DESC, eat ASC")
    else
      @photos = Photo.find(:all, :conditions => ["user_id = ?", current_user.id], :order => "day DESC, eat ASC")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end
  

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new
    
    @photo.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, :notice => 'Photo was successfully created.' }
        format.json { render :json => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, :notice => 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/calendar/_form.html.erb
<%= form_for(@calendar, :html => {:multipart => true}) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendar/create.html.erb
<h1>Calendar#create</h1>
<p>Find me in app/views/calendar/create.html.erb</p>

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1>Calendar</h1>

<%= raw(event_calendar) %>

app/views/calendar/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.hidden_field :good %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :photo_id, :value => @photo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Good</th>
    <th>User</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comment %></td>
    <td><%= comment.good %></td>
    <td><%= comment.user_id %></td>
    <td><%= comment.photo_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/comments/show.html.erb
<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>Good:</b>
  <%= @comment.good %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Photo:</b>
  <%= @comment.photo_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', photos_path %>

app/views/event/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    

      
<%= PLURALIZE(@EVENT.ERRORS.COUNT, "ERROR") %> PROHIBITED THIS POST FROM BEING SAVED:



      

      <% @event.errors.full_messages.each do |msg| %>
        
<%= msg %>

      <% end %>
      

    

  <% end %>

  

    <%= f.label :name %>

    <%= f.text_field :name %>
  

  

    <%= f.label :start_at %>

    <%= f.datetime_select :start_at %>
  


    <%= f.label :end_at %>

    <%= f.datetime_select :end_at %>
  

  

    <%= f.submit %>
  

<% end %>

app/views/event/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

app/views/event/index.html.erb
#Find

app/views/event/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', calendar_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fopic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">  
  <% if user_signed_in?%>  
    Signed in as <%= current_user.email %>. Not you?    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>  
  <% else %>  
    <%= link_to "Sign up", new_user_registration_path %> or  
    <%= link_to "Sign in", new_user_session_path %>  
  <% end %>  
</div>  

<p id="notice" class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>




</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => {:multipart => true}) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :picture_file %><br />
    <%= f.file_field :picture_file %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br />
    <%= f.text_field :explanation %>
  </div>
  
  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>

  <div class="field">
    <%= f.label :eat %><br />
    <% options = [["朝食", 1], ["昼食", 2], ["夕食", 3]] %>
    <%= f.select :eat ,options %>
  </div>

  
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table id="cal">


<% @photos.each do |photo| %>
  <% if @day != photo.day then %> <tr> <% end %>
    <td class="thum">
    <%= photo.day %>
    <% if photo.eat == 1 then %> 朝食<% end %>
    <% if photo.eat == 2 then %> 昼食<% end %>
    <% if photo.eat == 3 then %> 夕食<% end %>
    <br/>
    <%= link_to image_tag(picture_photo_path(photo), :height => '64'), photo %>
    
    </td>
  <% @day = photo.day %>
  <% if @day != photo.day then %> <tr> <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>
<br/>
<%= link_to "自分の写真を見る" , :action => "index", :filter => "only_me" %>
<%= link_to "全ての写真を見る" , :action => "index", :filter => "all" %>
<%= link_to "自分以外の写真を見る", :action => "index", :filter => "without_me" %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p>
  <b>タイトル</b>
  <%= @photo.title %>
</p>


<p>
  <%= @photo.day %>
</p>

<p>
  <% if @photo.eat==1 then %> 朝食 <% end %> 
  <% if @photo.eat==2 then %> 昼食 <% end %>
  <% if @photo.eat==3 then %> 夜食 <% end %>
  
</p>

<p>
  <%= image_tag picture_photo_path(@photo), :height => '240' %>
</p>

<p>
  <%= @photo.explanation %>
</p>
<hr>
<% @comments = @photo.comment %>
<% @comments.each do |comment| %>
  (<%= User.find(comment.user_id).email %>):
  <%= comment.comment %>
  <br/>
<% end %>

<br/>
<hr>
<%= link_to "コメントする", :controller => "comments" , :action => "new", :id => @photo.id %>
<br/>
<%= link_to 'Back', :back %> |
<% if @photo.user_id == current_user.id %>
  <%= link_to 'Edit', edit_photo_path(@photo) %> |
  <%= link_to 'Destroy', @photo, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
<% end %>